[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"
path = "src/ircbot.rs"


[dependencies]
hyper = "~0.0.1"
toml = "~0.1.3"
time = "~0.0.3"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"
