[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"
path = "src/ircbot.rs"


[dependencies]
toml = "~0.1.7"
time = "~0.1.4"
log = "~0.1.3"
rustc-serialize = "~0.1.0"
hyper = "~0.0.17"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"

[dependencies.dbus-rs]
git = "https://github.com/infinityb/dbus-rs"
branch = "experimental"
