[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"
path = "src/ircbot.rs"


[dependencies]
toml = "0.1.12"
time = "0.1.12"
url = "0.2.16"
rustc-serialize = "0.2.8"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"
