[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"


[dependencies]
toml = "0.1"
time = "0.1"
url = "0.2"
rustc-serialize = "0.3"
rand = "0.3"
hyper = "0.6"
mio = "0.3"
bytes = "*"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"

[dependencies.irc_mio]
git = "https://github.com/infinityb/rust-irc-mio"
