[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"
path = "src/ircbot.rs"


[dependencies]
toml = "0.1"
time = "0.1"
url = "0.2"
rustc-serialize = "0.3"
rand = "0.3"
hyper = "0.3"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
