[package]
name = "ircbot"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[[bin]]
name = "ircbot"
path = "src/ircbot.rs"


[dependencies]
toml = "~0.1.11"
time = "~0.1.12"
log = "~0.1.9"
rustc-serialize = "~0.2.7"
url = "^0.2"
# hyper = "~0.0.21"

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

# [dependencies.dbus-rs]
# git = "https://github.com/infinityb/dbus-rs"
# branch = "experimental"
